openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-8a9d.onrender.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    400:
      description: Bad Request error
      content:
        application/json:
          schema:
            type: object
            required:
              - status
              - message
              - data
            properties:
              status:
                type: integer
                example: 400
              message:
                type: string
                example: BadRequestError
              data:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Invalid input data
    404:
      description: Not Found error
      content:
        application/json:
          schema:
            type: object
            required:
              - status
              - message
              - data
            properties:
              status:
                type: integer
                example: 404
              message:
                type: string
                example: NotFoundError
              data:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Contact not found
security:
  - bearerAuth: []
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml
